version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"          # Root folder containing package.json
    schedule:
      interval: "weekly"    # Dependabot checks once per week
    commit-message:
      prefix: "deps"        # PR commit prefix (optional)
    open-pull-requests-limit: 10
